# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.8.0

    steps:
      - checkout
      - run: npm install
      - run: sh -c "npm start" & PID=$! && echo "PID is $PID and PWD is $PWD" && sleep 5
      - run: npm test
